echo Start server configurations...
echo Start admin front-end configurations...

echo Go to the admin front project...
cd /home/AdvancedWebProject/front-end/admin-front

echo Start building project...
ng build --prod
echo Building finished...
cd ./dist/

echo Remove previous deployed folder...
rm -r /var/www/angular-deploy-admin

echo Create new deploying folder...
mkdir /var/www/angular-deploy-admin

echo Move deployable files...
mv ./admin-front/* /var/www/angular-deploy-admin

cd ..
rm -r ./dist

echo Finished admin front-end configurations...

echo Start back-end configurations...

echo Stop pm2 backend instance...
pm2 stop 0

cd /home/AdvancedWebProject/back-end/bin/

echo Remove previous deployed file...
rm ./www

echo Create new deployable file...
mv ./www.example ./www

cd /home

echo Start pm2 backend instance...
pm2 start 0

echo Finished back-end configurations...

echo Finished server configurations...
echo Thank You...!!!